services:
  django:
    image: mojito-api:dev
    container_name: api
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: development
      args:
        - DJANGO_ENV=development
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      cache_from:
        - "mojito-api:dev"
        - "mojito-api:latest"
        - "*"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - main
    env_file:
      - config/.env
    command: python -Wd manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - main
    env_file:
      - config/.env
    restart: unless-stopped


volumes:
  data:

networks:
  main:
