services:
  django:
    container_name: api-django
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: development
      args:
        - DJANGO_ENV=development
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - database
    env_file:
      - .env
    command: python -Wd manage.py runserver 0.0.0.0:8000

  postgresql:
    image: postgres:16.2-alpine
    container_name: api-postgres
    volumes:
      - .data/postgresql:/var/lib/postgresql/data
    networks:
      - database
    env_file:
      - .env
    restart: unless-stopped

networks:
  database:
