assignees:
  - 'bitterteriyaki'

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug.
  - type: textarea
    attributes:
      label: Summary
      description: A simple summary of your bug report.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell-script
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/mojitoteam/.github/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

name: Bug Report
labels: [unconfirmed bug]

title: '[bug] '
description: Report broken or incorrect behaviour.
